import 'package:mango_test/model/user.dart' as localUser;
import 'package:mango_test/model/userRefrigerator.dart';

import 'food.dart';

List<Food> sampleFoodList = [
  Food(
    name: '레몬',
    registerDate: DateTime(-11),
    purchaseDate: DateTime(-12),
    DueDate: 12,
    num: 1,
    storeLevel: 2,
    category: '과일/채소',
    isSelected: true,
    selectedNum: 0,
  ),
  Food(
    name: '파프리카',
    registerDate: DateTime(0),
    purchaseDate: DateTime(-1),
    DueDate: 1,
    num: 3,
    storeLevel: 0,
    category: '과일/채소',
    isSelected: true,
    selectedNum: 0,
  ),
  Food(
    name: '오이',
    registerDate: DateTime(0),
    purchaseDate: DateTime(-7),
    DueDate: 7,
    num: 1,
    storeLevel: 2,
    category: '과일/채소',
    isSelected: true,
    selectedNum: 0,
  ),
  Food(
    name: '고추',
    registerDate: DateTime(-2),
    purchaseDate: DateTime(-14),
    DueDate: 12,
    num: 2,
    storeLevel: 0,
    category: '과일/채소',
    isSelected: true,
    selectedNum: 0,
  ),
  Food(
    name: '만두',
    shelfLife: DateTime(29),
    registerDate: DateTime(-2),
    purchaseDate: DateTime(-4),
    DueDate: 25,
    num: 1,
    storeLevel: 1,
    category: '냉장/냉동식품',
    isSelected: false,
    selectedNum: 0,
  ),
  Food(
    name: '앞다리살',
    shelfLife: DateTime(12),
    registerDate: DateTime(-11),
    purchaseDate: DateTime(-12),
    DueDate: 0,
    num: 1,
    storeLevel: 1,
    category: '냉장/냉동식품',
    isSelected: false,
    selectedNum: 0,
  ),
  Food(
    name: '고등어',
    shelfLife: DateTime(12),
    registerDate: DateTime(0),
    purchaseDate: DateTime(-2),
    DueDate: 10,
    num: 3,
    storeLevel: 1,
    category: '수산류',
    isSelected: false,
    selectedNum: 0,
  ),
];
