import 'package:mango_test/model/friends/trade.dart';
import 'package:mango_test/model/users/user.dart' as localUser;
import 'package:mango_test/model/users/userRefrigerator.dart';

import 'users/food.dart';

List<Food> sampleFoodList = [
  Food(
    name: '레몬',
    registerDate: DateTime(2021, 2, 15),
    purchaseDate: DateTime(2021, 2, 14),
    DueDate: 12,
    num: 1,
    storeLevel: 2,
    category: '과일',
    isSelected: true,
    // selectedNum: 0,
  ),
  Food(
    name: '파프리카',
    registerDate: DateTime(2021, 2, 15),
    purchaseDate: DateTime(2021, 2, 14),
    DueDate: 1,
    num: 3,
    storeLevel: 0,
    category: '채소',
    isSelected: true,
    // selectedNum: 0,
  ),
  Food(
    name: '오이',
    registerDate: DateTime(2021, 1, 25),
    purchaseDate: DateTime(2021, 1, 23),
    DueDate: 7,
    num: 1,
    storeLevel: 2,
    category: '채소',
    isSelected: true,
    // selectedNum: 0,
  ),
  Food(
    name: '고추',
    registerDate: DateTime(2021, 1, 27),
    purchaseDate: DateTime(2021, 1, 27),
    DueDate: 12,
    num: 2,
    storeLevel: 0,
    category: '채소',
    isSelected: true,
    // selectedNum: 0,
  ),
  Food(
    name: '만두',
    shelfLife: DateTime(2021, 6, 12),
    registerDate: DateTime(2021, 1, 27),
    purchaseDate: DateTime(2021, 1, 27),
    DueDate: 25,
    num: 1,
    storeLevel: 1,
    category: '냉장/냉동식품',
    isSelected: false,
    // selectedNum: 0,
  ),
  Food(
    name: '앞다리살',
    shelfLife: DateTime(2021, 2, 12),
    registerDate: DateTime(2021, 1, 27),
    purchaseDate: DateTime(2021, 1, 27),
    DueDate: 0,
    num: 1,
    storeLevel: 1,
    category: '냉장/냉동식품',
    isSelected: false,
    // selectedNum: 0,
  ),
  Food(
    name: '고등어',
    shelfLife: DateTime(2021, 2, 22),
    registerDate: DateTime(2021, 1, 27),
    purchaseDate: DateTime(2021, 1, 27),
    DueDate: 10,
    num: 3,
    storeLevel: 1,
    category: '수산물',
    isSelected: false,
    // selectedNum: 0,
  ),
];
